version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: sql_dev
    ports:
      - 15432:15432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dvdrental
    volumes:
      - $PWD/dvdrental.tar:/volumes/dvdrental.tar
